# Generated by Django 3.0.3 on 2020-02-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Python_Interview_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=254, null=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question', models.CharField(max_length=254)),
                ('option_a', models.CharField(max_length=254)),
                ('option_b', models.CharField(max_length=254)),
                ('option_c', models.CharField(max_length=254)),
                ('option_d', models.CharField(max_length=254)),
                ('answer', models.CharField(max_length=254)),
            ],
        ),
    ]
