# Generated by Django 3.0 on 2019-12-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Python_Interview_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Python_Interview_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('interview_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='python.Python_Interview_Question')),
            ],
        ),
    ]
