# Generated by Django 3.0 on 2019-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_question', models.CharField(max_length=254)),
                ('option_a', models.CharField(max_length=254)),
                ('option_b', models.CharField(max_length=254)),
                ('option_c', models.CharField(max_length=254)),
                ('option_d', models.CharField(max_length=254)),
                ('answer', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='python_interview_question_answer',
            name='interview_question',
        ),
        migrations.AddField(
            model_name='python_interview_question_answer',
            name='question',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Python_Interview_Question',
        ),
    ]
